# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CAD_CP_M.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from RECONNECT import reconnect
import MENSAGEM_CAIXA
import BANCO_TABLE
import sqlite3

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(616, 102)
        Dialog.setWindowIcon(QtGui.QIcon("images/moed.png"))
        Dialog.setMinimumSize(QtCore.QSize(616, 102))
        Dialog.setMaximumSize(QtCore.QSize(616, 102))
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog.setFont(font)
        Dialog.setModal(True)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 101, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 113, 25))
        self.lineEdit.setStyleSheet("QLineEdit:focus {\n"
                                    "    border: 2px solid rgb(0, 85, 255);\n"
                                    "    background-color: rgb(255, 255, 231);\n"
                                    "}")
        self.lineEdit.setMaxLength(10)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(200, 0, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(410, 0, 91, 21))
        self.label_3.setObjectName("label_3")
        self.pushButton_SALVAR = QtWidgets.QPushButton(Dialog)
        self.pushButton_SALVAR.setEnabled(False)
        self.pushButton_SALVAR.setGeometry(QtCore.QRect(580, 60, 31, 31))
        self.pushButton_SALVAR.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_SALVAR.setStyleSheet("QPushButton {\n"
                                             "    border: 1px solid rgb(240, 240, 240);\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:hover {\n"
                                             "    border: 1px solid rgb(45, 204, 112);\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:pressed {\n"
                                             "    border: 1px solid rgb(0, 255, 0);\n"
                                             "}")
        self.pushButton_SALVAR.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/sim.png"))
        self.pushButton_SALVAR.setIcon(icon)
        self.pushButton_SALVAR.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_SALVAR.setObjectName("pushButton_SALVAR")
        self.pushButton_CANCELA = QtWidgets.QPushButton(Dialog)
        self.pushButton_CANCELA.setGeometry(QtCore.QRect(540, 60, 31, 31))
        self.pushButton_CANCELA.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_CANCELA.setStyleSheet("QPushButton {\n"
                                              "    border: 1px solid rgb(240, 240, 240);\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton:hover {\n"
                                              "    border: 1px solid rgb(186, 0, 0);\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton:pressed {\n"
                                              "    border: 1px solid rgb(255, 0, 0);\n"
                                              "}")
        self.pushButton_CANCELA.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/nao.png"))
        self.pushButton_CANCELA.setIcon(icon1)
        self.pushButton_CANCELA.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_CANCELA.setObjectName("pushButton_pesq_dol")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 20, 201, 25))
        self.lineEdit_2.setStyleSheet("QLineEdit:focus {\n"
                                      "    border: 2px solid rgb(0, 85, 255);\n"
                                      "    background-color: rgb(255, 255, 231);\n"
                                      "}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(410, 20, 201, 25))
        self.lineEdit_3.setStyleSheet("QLineEdit:focus {\n"
                                      "    border: 2px solid rgb(0, 85, 255);\n"
                                      "    background-color: rgb(255, 255, 231);\n"
                                      "}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(410, 70, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 20, 61, 25))
        self.lineEdit_4.setStyleSheet("QLineEdit:focus {\n"
                                      "    border: 2px solid rgb(0, 85, 255);\n"
                                      "    background-color: rgb(255, 255, 231);\n"
                                      "}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(130, 0, 91, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 70, 201, 25))
        self.lineEdit_5.setStyleSheet("QLineEdit:focus {\n"
                                      "    border: 2px solid rgb(0, 85, 255);\n"
                                      "    background-color: rgb(255, 255, 231);\n"
                                      "}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(200, 50, 91, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 70, 181, 25))
        self.lineEdit_6.setStyleSheet("QLineEdit:focus {\n"
                                      "    border: 2px solid rgb(0, 85, 255);\n"
                                      "    background-color: rgb(255, 255, 231);\n"
                                      "}")
        self.lineEdit_6.setMaxLength(30)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit, self.lineEdit_4)
        Dialog.setTabOrder(self.lineEdit_4, self.lineEdit_2)
        Dialog.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Dialog.setTabOrder(self.lineEdit_3, self.lineEdit_6)
        Dialog.setTabOrder(self.lineEdit_6, self.lineEdit_5)
        Dialog.setTabOrder(self.lineEdit_5, self.pushButton_SALVAR)
        Dialog.setTabOrder(self.pushButton_SALVAR, self.pushButton_CANCELA)
        self.var_x = ""
        self.cod = ""

        # VALIDATOR SÓ INT
        self.lineEdit_4.setValidator(QtGui.QIntValidator())

        # VALIDATOR SÓ DOUBLE
        self.lineEdit_2.setValidator(QtGui.QDoubleValidator())
        self.lineEdit_3.setValidator(QtGui.QDoubleValidator())

        # CONEXÃO ATIVAR BOTÃO
        self.lineEdit.textChanged[str].connect(self.ativar_btn)
        self.lineEdit_6.textChanged[str].connect(self.ativar_btn)

        # CONEXÃO CALCULAR VALORES
        self.lineEdit_2.textChanged[str].connect(self.calcular_valor)
        self.lineEdit_3.textEdited.connect(self.calcular_real_dola)

        # CONEXÃO FORMATAR NUMEROS
        #self.lineEdit_2.editingFinished.connect(self.formatar_valores)
        #self.lineEdit_3.editingFinished.connect(self.formatar_valores)

        # CONEXÃO FECHAR
        self.pushButton_CANCELA.clicked.connect(Dialog.close)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit, self.lineEdit_4)
        Dialog.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Dialog.setTabOrder(self.lineEdit_3, self.lineEdit_6)
        Dialog.setTabOrder(self.pushButton_SALVAR, self.pushButton_CANCELA)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cadastrar Cripto Moeda"))
        self.label.setText(_translate("Dialog", "Simbolo Cripto"))
        self.label_2.setText(_translate("Dialog", "Valor/US$"))
        self.label_3.setText(_translate("Dialog", "Valor/R$"))
        self.pushButton_SALVAR.setShortcut(_translate("Dialog", "Enter"))
        self.pushButton_CANCELA.setShortcut(_translate("Dialog", "Esc"))
        self.label_5.setText(_translate("Dialog", "ID Cripto"))
        self.label_6.setText(_translate("Dialog", "Quantidade"))
        self.label_7.setText(_translate("Dialog", "Nome da Cripto"))

    def calcular_valor(self):
        try:
            if self.lineEdit_2.text():
                reconnect(self.lineEdit_3.textChanged, None)
                reconnect(self.lineEdit_3.textEdited, self.calcular_real_dola)
                dolar = self.var_x
                valor = float(self.lineEdit_2.text().replace(",", "."))
                tratamento = valor * dolar
                self.lineEdit_3.setText(str("{:_.12f}".format(float(tratamento)).replace("_", "")))
            else:
                self.lineEdit_3.setText("")
        except Exception as ERROR:
            print(ERROR)


    def calcular_real_dola(self):
        try:
            if self.lineEdit_3.text():
                reconnect(self.lineEdit_2.textChanged, None)
                reconnect(self.lineEdit_2.textEdited, self.calcular_valor)
                dolar = self.var_x
                valor = float(self.lineEdit_3.text().replace(",", "."))
                tratamento = valor / dolar
                self.lineEdit_2.setText(str("{:_.12f}".format(float(tratamento)).replace("_", "")))
            else:
                self.lineEdit_2.setText("")
        except Exception as ERROR:
            print(ERROR)



    def ativar_btn(self):
        if self.lineEdit.text() and self.lineEdit_6.text():
            self.pushButton_SALVAR.setEnabled(True)
        else:
            self.pushButton_SALVAR.setEnabled(False)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
